name: Update NBP base rates

on:
  workflow_dispatch:    # pozwala odpalić ręcznie w UI
  schedule:
    # Zima (listopad–luty): 17:00 CET = 16:00 UTC
    - cron: '0 16 * 11,12,1,2 *'
    # Lato (marzec–październik): 17:00 CEST = 15:00 UTC
    - cron: '0 15 * 3-10 *'

permissions:
  contents: write

jobs:
  update-nbp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Fetch and save NBP rates
        run: python fetch_nbp.py

      - name: Commit & push JSON
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add nbp_rates.json
          git commit -m "Daily NBP rates update" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
